# -- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * 30 * (100-D.DISCOUNT_RATE)/100 FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN (SELECT CAR_TYPE, REPLACE(DISCOUNT_RATE, "%", "") DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE = "30일 이상") D
            USING (CAR_TYPE)
WHERE CAR_TYPE IN ("세단", "SUV")
    AND C.DAILY_FEE * 30 * (100-D.DISCOUNT_RATE)/100 >= 500000
    AND C.DAILY_FEE * 30 * (100-D.DISCOUNT_RATE)/100 < 2000000
    AND CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
ORDER BY 3 DESC, 2, 1 DESC;