-- 코드를 입력하세요
WITH RECURSIVE TIME AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23)

SELECT TIME.HOUR, COUNT(ANIMAL_ID) `COUNT`
FROM TIME LEFT JOIN (
    SELECT ANIMAL_ID, HOUR(DATETIME) HOUR
    FROM ANIMAL_OUTS) D USING (HOUR)
GROUP BY 1
ORDER BY 1;