-- 코드를 입력하세요
# SELECT USER_ID, U.NICKNAME, SUM(B.PRICE) TOTAL_SALES
# FROM USED_GOODS_USER U JOIN USED_GOODS_BOARD (USING) USER_ID
# GROUP BY USER_ID

SELECT B.WRITER_ID, U.NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE `STATUS` = 'DONE'
GROUP BY 1
HAVING TOTAL_SALES >= 700000
ORDER BY 3;