-- 코드를 입력하세요
# SELECT O.CATEGORY, O.PRICE MAX_PRICE, O.PRODUCT_NAME
# FROM (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
#       FROM FOOD_PRODUCT
#       GROUP BY CATEGORY) X INNER JOIN FOOD_PRODUCT O
#       ON X.CATEGORY = O.CATEGORY AND X.MAX_PRICE = O.PRICE
# WHERE O.CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY 2 DESC;
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 2 DESC;