-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES S INNER JOIN BOOK B USING (BOOK_ID)
WHERE DATE_FORMAT(S.SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;